### ISSUE TITLE
There is a need (to be able to mark) for LAZY fetching (of associations)

### ISSUE THREAD

**Issue by haqer1** [arangodb/spring-data#11]
This would be consistent with FetchType.LAZY:
https://javaee.github.io/javaee-spec/javadocs/javax/persistence/FetchType.html
This could in fact be implemented using the same enum.

P.S. In JPA, this frequently works as follows:
lazily-fetched association (especially if it's to-many) isn't fetched right away, but if it's dereferenced, it's fetched at that moment (before dereferencing method returns); i.e., on as needed basis.
P.P.S. I haven't seen something similar to this in the current implementation, hence logging this here...

**Comment by mpv1989** [comment]
Hi @haqer1 ,

thanks for the feedback. The annotations [@Ref](https://arangodb.github.io/spring-data/javadoc-2_0/com/arangodb/springframework/annotation/Ref.html), [@Relations](https://arangodb.github.io/spring-data/javadoc-2_0/com/arangodb/springframework/annotation/Relations.html), [@From](https://arangodb.github.io/spring-data/javadoc-2_0/com/arangodb/springframework/annotation/From.html) and [@To](https://arangodb.github.io/spring-data/javadoc-2_0/com/arangodb/springframework/annotation/To.html) already support laziness which works the same as you mentioned.

best
Mark
