### ISSUE TITLE
ArangoExampleConverter not support  ExampleMatcher.StringMatcher.CONTAINING

### ISSUE THREAD

**Issue by Jeffsyl01** [arangodb/spring-data#113]
In ArangoExampleConverter.addPredicate
only support  STARTING、ENDING、DEFAULT、EXACT，not support  CONTAINING
`switch (stringMatcher) {
			case STARTING:
				value = "^" + escape(string);
				break;
			case ENDING:
				value = escape(string) + "$";
				break;
			case DEFAULT:
			case EXACT:
			default:
				value = "^" + escape(string) + "$";
				break;
			}`

**Comment by mpv1989** [comment]
Hi @Jeffsyl01,

thanks for reporting. The fix will be included in the next release.

best
Mark

**Comment by mpv1989** [comment]
fixed in 1.3.2 , 2.3.2 and 3.0.0
