### ISSUE TITLE
XML Configuration of ArangoDb collections

### ISSUE THREAD

**Issue by manishtha86** [arangodb/spring-data#114]
As an alternative to annotations, is there any plan to support xml configuration of ArangoDb collections (documents, edges, etc)?

**Comment by manishtha86** [comment]
Thanks for getting back Mark. While configuring the entity manager in Spring Data it does give you an option to specify the XML configuration file of your entity (e.g. when using hibernate, we use the .hbm.xml file) That way i have the option to not put an persistence layer specific annotations (e.g. @Entity, @Document, @Id, etc) in my model and i can share those with my service consumers (without them knowing or having to include any arango db or jpa jars.

**Comment by mpv1989** [comment]
Ok, but this is a hibernate and not Spring Data feature. We could think about implementing this feature in the underlying [arangodb-java-driver](https://github.com/arangodb/arangodb-java-driver).

Feel free to open a feature request issue in the corresponding [github repo](https://github.com/arangodb/arangodb-java-driver).
