### ISSUE TITLE
support spring 5.1.0

### ISSUE THREAD

**Issue by faquir-sun** [arangodb/spring-data#123]
Is there a plan to support spring 5.1.0 and spring data commons 2.1.0?
The other components of my project depend on the spring data commons 2.1.0 version, but the arangodb depends on the 2.0.7 version. I recompile the spring data arango using spring 5.1.0 and spring data commons 2.1.0, the compilation was successful, but the test case failed three.
1.
`Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 39.998 sec <<< FAILURE! - in com.arangodb.springframework.core.mapping.CustomMappingTest
vpackToDBEntity(com.arangodb.springframework.core.mapping.CustomMappingTest)  Time elapsed: 9.016 sec  <<< ERROR!
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type java.lang.Object!
	at com.arangodb.springframework.core.mapping.CustomMappingTest.vpackToDBEntity(CustomMappingTest.java:156)`
2.
`mutliUpsertWithUserGeneratedKey(com.arangodb.springframework.core.template.ArangoTemplateTest)  Time elapsed: 11.481 sec  <<< ERROR!
java.lang.UnsupportedOperationException: No accessor to set property @org.springframework.data.annotation.Id()private final java.lang.String com.arangodb.springframework.core.template.ArangoTemplateTest$NewEntityTest.id!
	at com.arangodb.springframework.core.template.ArangoTemplateTest.mutliUpsertWithUserGeneratedKey(ArangoTemplateTest.java:421)`
3.
`upsertWithUserGeneratedKey(com.arangodb.springframework.core.template.ArangoTemplateTest)  Time elapsed: 7.078 sec  <<< ERROR!
java.lang.UnsupportedOperationException: No accessor to set property @org.springframework.data.annotation.Id()private final java.lang.String com.arangodb.springframework.core.template.ArangoTemplateTest$NewEntityTest.id!
	at com.arangodb.springframework.core.template.ArangoTemplateTest.upsertWithUserGeneratedKey(ArangoTemplateTest.java:409)`

**Comment by mpv1989** [comment]
@faquir-sun thanks for reporting, I am working on it.

**Comment by faquir-sun** [comment]
@mpv1989 It‘s Great work. Thank you for your reply. I really look forward to it.

**Comment by mpv1989** [comment]
@faquir-sun I've created a PR #126

**Comment by runjia1987** [comment]
Seems still not resloved after these months.
See link: https://github.com/spring-projects/spring-boot/issues/15698

**Comment by rashtao** [comment]
The current version of Spring Data ArangoDB supports Spring 5.3 and `spring-data-commons` 2.4.5.
