### ISSUE TITLE
Can't remove attributes from a Map

### ISSUE THREAD

**Issue by bthj-tms** [arangodb/spring-data#133]
With an entity like:

```
@Document
@Data public class MapTest {
    @Id private String id;
    private Map<String, Boolean> aMap;
}
```

I can add entries to the map and a call to the repository's `.save` method updates the document in the database as expected.

If however I retrieve a document, remove an entry from the map and call `.save`, the returned results from that call are as expected, the entry has been removed, but the database document has not been updated, the deleted map entry is still there.

I've tried placing a new Map instance on the document before saving, but with no luck.

Is there something missing in my approach?

**Comment by mpv1989** [comment]
@bthj-tms This is a bug. `ArangoRepository.save()` is performing an _upsert_ instead of the expected _repsert_ with ArangoDB version < 3.4. I created PR #137 to fix this.
