### ISSUE TITLE
saveAll not working

### ISSUE THREAD

**Issue by bthj-tms** [arangodb/spring-data#141]
If perform a query and data updates like:
```
Iterable<SomeCollection> docs = repository.findAll().forEach( d -> {
  d.setSomeAttribute("qwerty");
});
```
and then save everything with:
```
repository.saveAll( docs );
```

then `someAttribute` is not updated, but if I do:
```
repository.findAll().forEach( d -> {
  d.setSomeAttribute("qwerty");
  repository.save( d );
});
```
then each document is updated as expected.

I'm using `arangodb-spring-data` version `3.1.1` against ArangoDB `3.4`

**Comment by J0s3f** [comment]
Same bug exists in version 3.2.1

**Comment by fceller** [comment]
@J0s3f can you check with 3.2.5?

**Comment by rashtao** [comment]
fixed in https://github.com/arangodb/spring-data/commit/412bdf57cff7c19cc94281e76361f2c3d0ece8cd

**Comment by osparking** [comment]
test
