### ISSUE TITLE
Nested property - Wrong AQL

### ISSUE THREAD

**Issue by npetillon** [arangodb/spring-data#143]
Hi,

When AQL generation with query to nested properties.

User Object: 
```typescript
{
  id: string,
  login : {
    email: string,
    password: string,
    ...
  },
  identity: {
    ...
  }
}
```

Repository :
```java
@Repository
public interface UserRepository extends ArangoRepository<User, String> {
    boolean existsByLoginEmailIgnoreCase(String login);
}
```

AQL generated : 
```sql
WITH login FOR e IN users FILTER LOWER(e.login.email) == @0 COLLECT WITH COUNT INTO length  RETURN length
```

Error : Query: AQL: collection or view not found: login (while parsing)

**Comment by oesolutions** [comment]
@npetillon I just encountered the same issue, did you ever get it resolved?

**Comment by rashtao** [comment]
Can you please provide some code snippet to reproduce the problem?
In general query derivation with nested properties is supported and tested, eg. here: https://github.com/arangodb/spring-data/blob/d399bb979353807625c9d8718fc214f427d01367/src/test/java/com/arangodb/springframework/repository/query/derived/DerivedQueryCreatorTest.java#L596-L605

**Comment by rashtao** [comment]
This is currently working and tested here: https://github.com/arangodb/spring-data/commit/d0d0ada88d133ce3de3aebc467da087b2364106a

Closing for now, please reopen in case of further problems.
