### ISSUE TITLE
NPE when empty "extra" object received with response

### ISSUE THREAD

**Issue by nikolko** [arangodb/spring-data#144]
Hi
When we use arango db v3.3.19 we have trouble with NPE in class AbstractArangoQuery when method logWarningsIfNecessary called.
It happens becouse this method try to get warnings from ArangoCursor. ArangoCursor contains stats and warnings in static class Extra, but our version of arango db send empty data for this object in response  - extra: {}. And we have NPE in method logWarningsIfNecessary .
More - methods getWarnings and getStats in ArangoCursor can return null's, and method logWarningsIfNecessary don't check this case:

    public Collection<Warning> getWarnings() {
        Extras extra = this.iterator.getResult().getExtra();
        return extra != null ? extra.getWarnings() : null;
    }

    

	private void logWarningsIfNecessary(final ArangoCursor<?> result) {
			result.getWarnings().forEach(warning -> {
				LOGGER.warn("Query warning at [" + method + "]: " + warning.getCode() + " - " + warning.getMessage());
			});
	}

We fixed it localy. Can i create pull request to solve this problem in project?

**Comment by rashtao** [comment]
Fixed by https://github.com/arangodb/arangodb-java-driver/commit/a32bb3d2374b53636f89b8236e8acbdac775299b
