### ISSUE TITLE
[Question] Roadmap

### ISSUE THREAD

**Issue by npetillon** [arangodb/spring-data#148]
Unfortunately, I don't see much activity on this repository.
Do you have any roadmap?
Is it an active repository?

**Comment by bthj** [comment]
Support for Spring Data will revitalize soon, according to @MrPieces.

**Comment by rashtao** [comment]
At the moment we are working at a new reactive driver version that will allow `spring-data-arangodb` to support reactive Spring Data repositories. 
You can follow the development here: https://github.com/arangodb/arangodb-java-driver/tree/next

**Comment by rashtao** [comment]
The development of new features will be based on the topics from GH issues tagged with `enhancement`. 
Closing for now, please continue the discussion in the related enhancement issue you are interested to or open a new one for further suggestions.
