### ISSUE TITLE
Query Syntax exception for <S extends T> Page<S> findAll(Example<S> var1, Pageable var2)

### ISSUE THREAD

**Issue by upadhyaydhiren** [arangodb/spring-data#153]
I tried with query by example but its throw query syntax exception.
Here is some pseudo class.
This is first class 

``` java
@Getter
@Setter
@Document(collection = "task")
public class Task {

    @Id
    private String id;

    private String name;

    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date dueDate;

    private Set<String> labels;

    private TaskStatus status;

    private Priority priority;

    @Ref
    private User user;
}
```

``` java
@Getter
@Setter
@Document(collection = "user")
public class User {

    @Id
    private String id;
    private String firstName;
    private String lastName;
}
```
I tried query for ref field of Task field.

```java
 ExampleMatcher exampleMatcher = ExampleMatcher.matchingAll();
  Task task = new Task();
  User user = new User();
  user.setId(123);  
  task.setUser(user); 
  Example<Task> tasks = Example.of(task, exampleMatcher);
  return taskDao.findAll(tasks, pageable);
```

When I executed AQL exception. Syntax error near limit. When I tried to debug I found for @Ref property in SimpleArangoRepository ArangoExampleConverter did not return correct predicate string 
Finally Query formed like 
```javascript
FOR e IN task FILTER LIMIT 0, 20 RETURN e
```
This is wrong query. If any one faced this issue or any earlier ticket. I feel in ArangoExampleConverter traversePropertyTree required fixed.

**Comment by upadhyaydhiren** [comment]
I fixed this issue. (https://github.com/arangodb/spring-data/pull/154)

**Comment by rashtao** [comment]
Thanks for contributing, PR merged!

**Comment by upadhyaydhiren** [comment]
Thanks @rashtao , Closing this issue
