### ISSUE TITLE
META-INF/spring.factories missing

### ISSUE THREAD

**Issue by hanyu-natsu** [arangodb/spring-data#155]
Spring data commons scans spring.factories in classpath to see if multiple spring data modules are loaded to enter strict configuration mode (by strictly checking the repository interface). 

While I have both spring-data-mongodb and arangodb-spring-data in the classpath, the RepositoryConfigurationDelegate detects only mongodb as spring data module. Thus the delegate tries to configure my arango repositories as mongo repositories.

There should be a spring.factories file in src/main/resources/META-INF to declare:
org.springframework.data.repository.core.support.RepositoryFactorySupport=com.arangodb.springframework.repository.ArangoRepositoryFactory

**Comment by rashtao** [comment]
Thanks for reporting, fixed by https://github.com/arangodb/spring-data/commit/bf13537e8918410472685074b5e5fa8391686200
