### ISSUE TITLE
Spring boot 2.1.8 artifacts issues

### ISSUE THREAD

**Issue by aboussofara** [arangodb/spring-data#159]
What's the difference between these artifacts :
- arangodb-spring-boot-starter
AND
- arangodb-spring-data

I Had to swith from arangodb-spring-data to arangodb-spring-boot-starter to be able to use Query annotation otherwise my app does not start !!!!

**Comment by rashtao** [comment]
arangodb-spring-boot-starter provides Spring AutoConfigurations and ConfigurationProperties. If you use `arangodb-spring-data` alone, you have to configure stuff manually by yourself, eg. check how it is done in the tests: https://github.com/arangodb/spring-data/blob/master/src/test/java/com/arangodb/springframework/ArangoTestConfiguration.java
