### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by cmdhitman** [arangodb/spring-data#165]
Hi, guys. Can we run ArangoRepository in multiple threads? Is it thread safe ?

For example 

```java
  @Async("ThreadPoolExecutor")
    public Future<List<Entity>> getAsync() {
        return new AsyncResult<>(repository.findAll());
    }
````

**Comment by rashtao** [comment]
Yes, it is thread safe. You can check its implementation here:

https://github.com/arangodb/spring-data/blob/974b05cd1389c9ddc88243bb286ec3a517133a2e/src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java

which delegates the template:

https://github.com/arangodb/spring-data/blob/19e27623de1e2532ee41b0e4fba115464884fcaf/src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.

**Comment by ndtreviv** [comment]
I'm, getting errors: `1200 - AQL: timeout waiting to lock key` which are related to write-write conflicts. 
Is the arangodb spring-data library using the java driver's async capabilities?

**Comment by rashtao** [comment]
Spring Data ArangoDB uses the synchronous driver.
This error is generated from the db side due to concurrent requests trying writing the same document.
Please refer to the related discussion about the topic in ArangoDB repository: https://github.com/arangodb/arangodb/issues/9702
