### ISSUE TITLE
Package protected constructor gives Exceptions

### ISSUE THREAD

**Issue by dvbeek** [arangodb/spring-data#167]
Hello, as far as I can tell from the documentation (i.e. https://download.arangodb.com/nightly/doc/ArangoDB_Drivers_devel.pdf, page 111), it is allowed to have a package protected constructor for persisted objects. But whenever I try to load objects from the database with a class that has multiple constructors, with a package protected default constructor marked with the PersistenceConstructor annotation, an exception is thrown.

VPack is just doing 'entity = ((Class)type).newInstance();', which leads to a IllegalAccessException.

Can you tell me if I'm doing something wrong, or misinterpreted the documentation or something?

We're using velocypack version 1.4.3, but I've also tried with version 2.1.0.

The constrcutors:
```
public class MyClass extends MySuper {

      @PersistenceConstructor
    MyClass() {
        super();
    }

    public MyClass(@NotNull X x, @NotNull Y y) {
        super(x, y);
    }
```

Exception:
> com.arangodb.ArangoDBException: com.arangodb.velocypack.exception.VPackParserException: java.lang.IllegalAccessException: class com.arangodb.velocypack.VPack cannot access a member of class a.b.c.MyClass with modifiers ""
> 	at com.arangodb.internal.util.ArangoDeserializerImpl.deserialize(ArangoDeserializerImpl.java:59)
> 	at com.arangodb.internal.util.DefaultArangoSerialization.deserialize(DefaultArangoSerialization.java:58)
> 	at com.arangodb.internal.cursor.ArangoCursorIterator.deserialize(ArangoCursorIterator.java:79)
> 	at com.arangodb.internal.cursor.ArangoCursorIterator.next(ArangoCursorIterator.java:75)
> 	at com.arangodb.internal.cursor.ArangoCursorImpl.next(ArangoCursorImpl.java:112)
> Caused by: com.arangodb.velocypack.exception.VPackParserException: java.lang.IllegalAccessException: class com.arangodb.velocypack.VPack cannot access a member of class  a.b.c.MyClass with modifiers ""
> 	at com.arangodb.velocypack.VPack.deserialize(VPack.java:408)
> 	at com.arangodb.internal.util.ArangoDeserializerImpl.deserialize(ArangoDeserializerImpl.java:55)
> 	... 60 more
> Caused by: java.lang.IllegalAccessException: class com.arangodb.velocypack.VPack cannot access a member of class  a.b.c.MyClass with modifiers ""
> 	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
> 	at java.base/jdk.internal.reflect.Reflection.ensureMemberAccess(Reflection.java:99)
> 	at java.base/java.lang.Class.newInstance(Class.java:579)
> 	at com.arangodb.velocypack.VPack.createInstance(VPack.java:510)

**Comment by rashtao** [comment]
Here you can find a working example: https://github.com/arangodb/spring-data/blob/5d3f720faa6b21d68ecd42f17277c0d221db5a42/src/test/java/com/arangodb/springframework/debug/repository/PersistenceConstructorClass.java

Also I can see that you have `com.arangodb.velocypack.VPack.createInstance` in your error stacktrace, but I would expect the entity to be instantiated by `org.springframework.data.convert.ClassGeneratingEntityInstantiator#createInstance`. Can you please add a snippet to exactly reproduce your error?

**Comment by dvbeek** [comment]
I just found out the Arango spring-data is not a part of the Arango Java driver.
Turns out we don't use this in our project, so I cannot use the annotation... My bad!
