### ISSUE TITLE
Save method doesn't return variables annotated by "@Relations"

### ISSUE THREAD

**Issue by gfitrz** [arangodb/spring-data#169]
Hi,
I have problem with "save" method and annotation "@Relations". When I save it doesnt return objects for variables that are annotated by this annotation.
Hopefuly when I save it by my own written method with annotation query it does return it.

**Comment by rashtao** [comment]
The `@Relations` annotation is only considered for reading operations. You need to save the related edges manually.
You can check this as example: https://github.com/arangodb/spring-data/blob/d399bb979353807625c9d8718fc214f427d01367/src/test/java/com/arangodb/springframework/repository/query/derived/DerivedQueryCreatorTest.java#L725-L730

**Comment by gfitrz** [comment]
Yes, but that is not what I meant. I mean that they are already saved in db, but when I do save it doesn't retrieves it. Even when I do save the key is not returned, it just returns the same object what I send. 
I use java 13, arango spring data 3.2.3, spring boot 2.2.2.RELEASE

**Comment by rashtao** [comment]
Let me clarify:
- saving an entity having fields annotated with `@Relations` does not produce any update to the related edge collection
- when you save an entity, the same entity is returned, check [here](https://github.com/arangodb/spring-data/blob/974b05cd1389c9ddc88243bb286ec3a517133a2e/src/main/java/com/arangodb/springframework/repository/SimpleArangoRepository.java#L91), so you may be confused seeing the field annotated with `@Relations` having the same value that you set, but actually that could not be the current db value
- when you save an entity key, rev and id of your entity are updated, as you can see [here](https://github.com/arangodb/spring-data/blob/19e27623de1e2532ee41b0e4fba115464884fcaf/src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java#L715-L726)

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
