### ISSUE TITLE
There has to be a support for automatic inheritance mapping (similar to (e.g.) JPA): after child class (document) instance is persisted, parent (compile-time) class (document) instance is auto-retrieved

### ISSUE THREAD

**Issue by haqer1** [arangodb/spring-data#17]
E.g., given the following example (simplified) classes:
@ Document("Parent")
class Parent {
String one;
}
@ Document("Child")
class Child extends Parent {
String two;
}
@ Document("Aggregate")
class Aggregate { 
@ Ref
Parent child;
}

After saving an instance of Aggregate with child (having property two), an instance with a ref key like Child/4214688 is persisted (e.g., under aggregate with key like Aggregate/4214696). But when retrieving the data for key Aggregate/4214696, it ends up having a child property of type Parent (thus not providing property Child.two).
Frankly, based on type in the key value, i expected the child property of type Child. This would be similar to 
https://docs.oracle.com/javaee/5/api/javax/persistence/InheritanceType.html#TABLE_PER_CLASS

The way it's now, there seems to be no support for (automatically handled) inheritance with ArangoDB. E.g., in JPA there are 3 options for automatic inheritance mapping:
https://docs.oracle.com/javaee/5/api/javax/persistence/InheritanceType.html

I haven't tried a custom query (with joins etc.) yet, but even if that works, developers shouldn't be burdened with that kind of work in this day and age, IMHO.

P.S. Document annotation might be mangled by the system here. To be clear, the following is meant:
https://github.com/arangodb/spring-data#document
Same for Ref:
https://github.com/arangodb/spring-data#reference

**Comment by mpv1989** [comment]
Thanks for reporting. I'll put this feature on our todo list with high priority

**Comment by christian-lechner** [comment]
I think this can be closed, as it is fixed by #33.

**Comment by haqer1** [comment]
This issue is not closed until PR 18 is merged: PR #33 is not a solution for this issue, & i'd never use such a data-polluting approach.
