### ISSUE TITLE
Possibility to config and use importDocuments

### ISSUE THREAD

**Issue by onospoo** [arangodb/spring-data#170]
Hello,
I have a difficult situation with arango spring-data, in particular with setting up and using function `importDocuments` defined in `ArangoCollection` in **arangodb-java-driver**. I have no possibillity to call it in `ArangoOperation`. I could get `ArangoCollection` from `ArangoTemplate` by call function `_collection` and then  call `importDocuments`, but method `_collection` is private and I can only access it through using reflection.
Can you do something with it, give some  possibility to call this function from `ArangoTemplate`(ex. make method `_collection` protected) or maybe some alternative to insert documents with posibility to ignore it on duplicate?

**Comment by rashtao** [comment]
You can access the underlying driver calling `.driver()` on ArangoTemplate: https://github.com/arangodb/spring-data/blob/19e27623de1e2532ee41b0e4fba115464884fcaf/src/main/java/com/arangodb/springframework/core/template/ArangoTemplate.java#L303

So you can do something like:
```java
template.driver().db("dbName").collection("collectionName").importDocuments(...)
```

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
