### ISSUE TITLE
@HashIndex annotation and shard keys

### ISSUE THREAD

**Issue by oliverlockwood** [arangodb/spring-data#173]
Since adding sharding to our collections, we started getting errors in a number of parts of our system where we use custom configurations of hash indexes.  Prior to introducing sharding >1, or on a single-node instance of ArangoDB, hash indexes could be configured without including the shard key; after sharding >1 on a cluster of >1 nodes, that is no longer be allowed.

In the context of `spring-data-arangodb` context, this occurs where we're using the `@HashIndex` annotation.

Specifically the errors are as follows:
```
com.arangodb.ArangoDBException: Response: 400, Error: 1470 - shard key '_key' must be present in unique index
```

The documentation in https://www.arangodb.com/docs/stable/drivers/spring-data-reference-mapping-indexes.html makes no reference to the need to include shard keys in such indices.  Eventually (see https://github.com/arangodb/arangodb/issues/11363) I found the relevant documentation in the core of Arango documentation.

I see that it is possible to use the `@Document` annotation to set specific `shardKeys`, which is probably the correct solution for most users.

It seems to me that:
- at the very least, there is a gap in documentation of usage of the `@HashIndex` annotation, for users of sharded ArangoDB clusters (which surely encompasses most non-trivial usecases)
- it's unclear how (through `spring-data-arangodb`) to create a `@HashIndex` to include `_key`, if that's what you want to do.  (And similarly for the `@HashIndexed` approach, etc.)

I'd welcome your thoughts.  Thank you in advance.

**Comment by rashtao** [comment]
As stated here: https://www.arangodb.com/docs/3.6/architecture-deployment-modes-cluster-sharding.html#indexes-on-shards :

> Unique indexes (hash, skiplist, persistent) on sharded collections are only allowed if the fields used to determine the shard key are also included in the list of attribute paths for the index

**Comment by oliverlockwood** [comment]
@rashtao yes, as mentioned, I eventually found that.

However I think we should at very least be linking to that documentation from the `spring-data-arangodb` docs which describe how to create custom indexes, and document that the way to customise your shard keys is via an option on the `@Document` annotation.

There is also my second question:
- It's unclear how (through `spring-data-arangodb`) to create a @HashIndex to include _key, if that's what you want to do. (And similarly for the @HashIndexed approach, etc.)

**Comment by rashtao** [comment]
The documentation related to indexes annotations is here: https://www.arangodb.com/docs/stable/drivers/spring-data-reference-mapping-indexes.html

`@Document` fields map one to one the collection options available from the driver and they are documented in the javadoc (https://arangodb.github.io/spring-data/javadoc-3_2/com/arangodb/springframework/annotation/Document.html#shardKeys--), which is also released to maven central together with the spring-data module, so it should be available to your IDE if you fetch sources along with `arangodb-spring-data` maven dependency.

Would you suggest any addition to it?

**Comment by oliverlockwood** [comment]
@rashtao yes.

I would would add a pointer to the https://www.arangodb.com/docs/stable/drivers/spring-data-reference-mapping-indexes.html page to mention the relationship with shard keys in a sharded setup - even just as a link to other documentation.

**Comment by rashtao** [comment]
I created this PR https://github.com/arangodb/docs/pull/501
Feel free to comment and share your feedback.
