### ISSUE TITLE
Dependency convergence error for com.arangodb:velocypack:1.4.2

### ISSUE THREAD

**Issue by ddinger** [arangodb/spring-data#174]
When using the maven enforcer plugin with my build I get the following warning

  +-com.arangodb:arangodb-spring-data:3.2.3
    +-com.arangodb:arangodb-java-driver:6.3.0
      +-com.arangodb:velocypack:1.4.2
and
+-de.leanbyte:leanbyte:0.0.1-SNAPSHOT
  +-com.arangodb:arangodb-spring-data:3.2.3
    +-com.arangodb:velocypack-module-jdk8:1.1.0
      +-com.arangodb:velocypack:1.1.0
and
+-de.leanbyte:leanbyte:0.0.1-SNAPSHOT
  +-com.arangodb:arangodb-spring-data:3.2.3
    +-com.arangodb:velocypack-module-joda:1.1.1
      +-com.arangodb:velocypack:1.1.0

For me this sounds like that within the dependency tree of spring-data-arangodb different versions of velocitypack are used.

The next question I have is that, why Version 1.4.2 is used, since there seems to be a 2.x version already.
Best regards,
Dirk

**Comment by rashtao** [comment]
Thanks for reporting, fixed in https://github.com/arangodb/spring-data/releases/tag/v3.2.4 and https://github.com/arangodb/spring-boot-starter/releases/tag/v1.0.3
