### ISSUE TITLE
Missing data in deserialised BaseDocument

### ISSUE THREAD

**Issue by alexandru-tetelea** [arangodb/spring-data#176]
We are executing a query which should return an object with a GeoJson inside of it.
The raw returned response is correct, with all coordinates which are present in db (executed via curl.)
But the BaseDocument object returned by Interface Repository (ArangoRepository<BaseDocument, String>) is missing the last coordinate from the GeoJson.

The structure of GeoJson coordinates is requiring that the first and last elements of GeoJson to be equal, and I saw that in DefaultArangoConverter the method ```private Object readCollection(final TypeInformation<?> type, final VPackSlice source)``` is creating a `LinkedHashSet` collection to store the coordinates. I think that last entry is ignored because hash code is the same as of the first one.

We are using the arangodb-spring-data:3.2.4 .

**Comment by rashtao** [comment]
@alexandru-tetelea thanks for spotting it! 
Can you please check if https://github.com/arangodb/spring-data/pull/179 solves your problem?
