### ISSUE TITLE
How to do one query on a view combind with tow collection.

### ISSUE THREAD

**Issue by lidaling** [arangodb/spring-data#187]
The view links is :
```
"links": {
    "v_people": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "name": {
          "analyzers": [
            "text_zh"
          ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    },
    "v_product": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "name": {
          "analyzers": [
            "text_zh"
          ]
        },
        "language": {
          "analyzers": [
            "text_zh"
          ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    }
  }
```
Create one entity do fits all fields with tow collection is not one good solution, I thought.
Anybody has one good idea,thanks.

**Comment by joerg84** [comment]
Thanks, we are looking into this.

**Comment by rashtao** [comment]
I am not sure if I understand the question correctly. 
Consider that views can be queried using AQL using the `@Query` annotation. This offers a lot of flexibility, eg. you can filter by entity type, use subqueries, perform joins, etc.
The returned data will be mapped to entities by Spring Data ArangoDB.

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
