### ISSUE TITLE
UNSET_RECURSIVE() does not work !

### ISSUE THREAD

**Issue by brunoaduarte** [arangodb/spring-data#188]
I'm trying to use the UNSET_RECURSIVE() method when building a custom query and it has NO effect on the results, just doesn't work.

I have the following classes:

```
@Document("users")
public class User {
	@Id String id;
	@Ref Collection<UserPhone> userPhones;
	String name;
}

@Document("usersPhones")
public class UserPhone {
	@Id String id;
	@Ref Phone phone;
	String phoneOwnerName;
}

@Document("phones")
public class Phone {
	@Id String id;
	@Ref Collection<CallLog> callHistory;
	String number;
}

@Document("callLogs")
public class CallLog {
	@Id String id;
	int duration;
	Date startedAt;
}
```

I need to retrieve all the UserPhone's registered to a specific User, but to exclude the CallLog (that will be a very long list). So i did

```
public interface UserPhone Repository extends ArangoRepository<UserPhone, String> {
	
	@Query("FOR u IN users " + 
		  "    FOR up IN usersPhones  " + 
			
		      "FILTER u.`key` == @value " + 
		      "FILTER up.`_id` IN u.userPhones" + 

		      "RETURN UNSET_RECURSIVE(up , 'callHistory')")

	Iterable<UserPhone> findAllByUserNoLog(@Param("value") String id);

}
```

But it does not work. The callHistory list is still queried creating a huge unecessary overhead to my request.

**Comment by rashtao** [comment]
Your AQL query does not read any `Phone` or `CallLog`, so `UNSET_RECURSIVE` does not change the `up` content in any way.
In your query the `up` variable is something like: 
```
  {
    "_class": "a.b.c.UserPhone",
    "_id": "usersPhones/1234",
    "_key": "1234",
    "_rev": "_bla---",
    "phone": "phones/9876",
    "phoneOwnerName": "owner"
  }
``` 

Therefore in the subsequent mapping of such JSON object to `UserPhone`, SpringDataArangoDB eagerly fetches the referenced entity `Phone` and on cascade `CallLog`.

As tip to debug custom queries proficiently, I would recommend you enabling the debug log level and checking the generated queries (and related returned data from the db).

**Comment by brunoaduarte** [comment]
Ok @rashtao thanks!
