### ISSUE TITLE
Cannot insert multiple documents into the specified Collection

### ISSUE THREAD

**Issue by Korov** [arangodb/spring-data#204]
Why not support inserting multiple documents into the specified Collection，
like this:
`<T> MultiDocumentEntity<? extends DocumentEntity> insert(String collectionName, Iterable<T> values, DocumentCreateOptions options)
			throws DataAccessException;`

**Comment by rashtao** [comment]
It is supported specifying the entity class: https://arangodb.github.io/spring-data/javadoc-3_3/com/arangodb/springframework/core/ArangoOperations.html#insert-java.lang.Iterable-java.lang.Class-com.arangodb.model.DocumentCreateOptions-

**Comment by Korov** [comment]
I want to insert Documents into different Collection monthly, but the @Document annotation cannot change the name of the table Collection，like Collection_202008,Collection_202009

**Comment by Korov** [comment]
The Document ID in Edge will also be affected by the `@Document` annotation, but I want to specify the Collection of Document in Edge

**Comment by Korov** [comment]
The amount of data in a single Collection is very large, resulting in very slow query speed, so I want to separate the Collection by month

**Comment by rashtao** [comment]
For such specific needs I would recommend you using the underlying Java driver directly. 
You can access it from https://arangodb.github.io/spring-data/javadoc-3_3/com/arangodb/springframework/core/ArangoOperations.html#driver--

Also note that if you want to keep Spring Data serialization while using the driver, you should manually delegate entity serialization and deserialization to `ArangoConverter`. For this, you can inject `ArangoConverter` and call respectively `write` and `read` methods on it.

**Comment by Korov** [comment]
Thanks, I will try to use it

**Comment by rashtao** [comment]
Another possible way to work around it, is to use SPEL expression in the collection name, see 
https://github.com/arangodb/spring-data/blob/7224786a3207413b8a79a429f2341b459a75cb6b/src/test/java/com/arangodb/springframework/core/mapping/MultiTenancyCollectionLevelMappingTest.java#L40

For example, the SPEL expression could include value coming from a bean method invocation, which returns the name of the month.
