### ISSUE TITLE
Sorting by array field - wrong AQL

### ISSUE THREAD

**Issue by dkalinina** [arangodb/spring-data#208]
Hi.
I have trouble with sorting by array fields.

That's simple form of my document
```
{
   "values": [
         {"date": "2020-11-03", "action": "delete"},
         {"date": "2020-09-01", "action": "edit"},
         {"date": "2020-04-17", "action": "add"}
   ]
}
```

And I use search with sorting
```
PageRequest pageable = PageRequest.of(0, 1,  Sort.by(Sort.Order.desc("values[0].date")));
repository.findAll(pageable);
```
Sort string is escaped in [_private static String escapeSortProperty(final String str)_ in _com.arangodb.springframework.core.util.AqlUtils_](https://github.com/arangodb/spring-data/blob/master/src/main/java/com/arangodb/springframework/core/util/AqlUtils.java#L117). And result string is wrong - it is _\`values[0]\`.\`date\`_ but it should be _\`values\`[0].\`date\`_.

**Comment by rashtao** [comment]
Thanks for reporting @dkalinina ,
it should be fixed by https://github.com/arangodb/spring-data/pull/209
