### ISSUE TITLE
ArangoRepository for inherited class brings records from base class

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [arangodb/spring-data#211]
# Steps to simulate

Given these four documents:

```
@Document(value="trainParts")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class TrainPart {

    @Id
    protected String id;

    @Ref
    protected TrainTechnology trainTechnology;
}

@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class TrainEngine extends TrainPart {

    public TrainEngine(String id, TrainTechnology trainTechnology) {
        super(id, trainTechnology);
    }
}

@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class TrainFuelCar extends TrainPart {

    public TrainFuelCar(String id, TrainTechnology trainTechnology) {
        super(id, trainTechnology);
    }
}

@Document(value="trainTechnologies")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class TrainTechnology {

    @Id
    private String id;
    private String name;
    private Integer speed;
    private Integer baseCapacity;
    private Integer baseFuel;
    private Integer peerEngines;
    private Integer fuelCars;
}
```

And these three repositories:

```
public interface TrainEnginesRepository extends ArangoRepository<TrainEngine, String> {
}

public interface TrainFuelCarsRepository extends ArangoRepository<TrainFuelCar, String> {
}

public interface TrainTechnologiesRepository extends ArangoRepository<TrainTechnology, String> {
    TrainTechnology findByName(String name);
}
```

After inserting a record using the following:

```
TrainTechnology trainTechnology = trainTechnologiesRepository.findByName("Existing Train Technology");
TrainEngine trainEngine = new TrainEngine(null, trainTechnology);
trainEnginesRepository.save(trainEngine);
```

The record is inserted successfully as a `TrainPart`. Checking from `arangosh`:

```
127.0.0.1:8529@trains> db.trainParts.all().toArray()
[
  {
    "_key" : "32991",
    "_id" : "trainParts/32991",
    "_rev" : "_bh3x2S6---",
    "_class" : "leonel.pockettrainsarango.model.TrainEngine",
    "trainTechnology" : "trainTechnologies/29927"
  }
]
```

However, when I try to fetch records that are `TrainFuelCar` documents with something like this:

```
List<TrainFuelCar> trainFuelCars = new ArrayList<>();
trainFuelCarsRepository.findAll().forEach(trainFuelCars::add);
```

I get back the `TrainEngine` document I've inserted previously.

Am I doing something wrong here? Is there something missing? In theory, the repository should not be retrieving `TrainEngine` documents as `TrainFuelCar` documents.

My test is here: https://github.com/leonelsanchesdasilva/pocket-trains-arango

**Comment by rashtao** [comment]
The query generated by `trainFuelCarsRepository.findAll()` is the following:
```
FOR c IN trainParts RETURN c
```
You can see it enabling debug log levels. This is because repositories are not aware of polymorphic entities, therefore generated queries do not filter by type.

Furthermore it could lead to deserialization exceptions, eg. in case the children classes of `TrainPart` have different fields. 

To avoid such issues, you could use one single repository for `TrainPart` and all its children and write custom queries when you need to filter by subtype. Eg:

```
public interface TrainPartsRepository extends ArangoRepository<TrainPart, String> {

    @Query("FOR c IN #collection FILTER c._class == \"leonel.pockettrainsarango.model.TrainFuelCar\" RETURN c")
    Iterable<TrainFuelCar> findAllTrainFuelCars();

    // ...

}
```

**Comment by leonelsanchesdasilva** [comment]
This worked. Is it possible to incorporate the detection of polymorphic entities in the Repository implementation, as it is for other JPA implementations?

**Comment by rashtao** [comment]
Spring Data has no API specification about it and the JPA inheritance strategies would be not a perfect fit for NOSQL data models.
Also automatically adding filter clauses to every generated query would be a problem for the cases when you want to have generic queries (eg. in your case `TrainPartsRepository.findAll() should return `Iterable<TrainPart>` containing instances of all its subclasses).

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
