### ISSUE TITLE
Why @Relations is not related to an Edge but another document

### ISSUE THREAD

**Issue by QAQtutu** [arangodb/spring-data#217]
I want to associate an edge in a document instead of another document.
If I use @Relations to get a document, I cannot query the edges between the two documents, because there may be many edges between them

**Comment by rashtao** [comment]
This is not supported by the current API. You should be able to perform it writing a custom traversal AQL query using the `@Query` annotation (see https://www.arangodb.com/docs/stable/drivers/spring-data-reference-repositories-queries.html).

**Comment by rashtao** [comment]
Closing for now, please reopen in case you have further questions.
