### ISSUE TITLE
findAllById(Collection<> ids) not working as expected

### ISSUE THREAD

**Issue by DevOps-TauRes** [arangodb/spring-data#218]
Hi folks,
I tried to find a solution with merge request, but was not able to find a suitable option in `DocumentReadOption` to get an IN comparism in AQL.

The problem ist, that the default search for `findAllById(Collection<> ids)` which should be search for _keys is not working as expected.
In Arango Logging we got this debug messages.
```
cat <<-___EOB___ | curl -X POST --dump - -u cat:LKJBD@JKbgjkbrjkbfkjBNJKhdf745* -d @- 'http://dev-arango-db-proxy.dev-databases.svc.cluster.local:80/_db/companies-and-tariffs/_api/cursor'
{"bindVars":{"0":["89af4b8c-c618-49ba-83b2-ee0f6de1cfdd","16fb5459-f30d-4348-9ba2-ee456d122627","6d281f3f-2ab3-466f-be6a-a2d5901cbeed","9d2788d7-7b21-4db3-bf7b-57992aa74f1e","8ecce6a0-8891-44b4-b71a-d1e90fc1b4b1","bcb5b6f9-1e0b-4653-81e1-57546ea650bb","e7906910-a654-47c6-817e-48f694ed0709","bd6b0feb-ec65-4a2e-9aa3-26737f267e52"]},"query":"FOR e IN company_type FILTER e._key == @0  RETURN e"}
___EOB___
```

A workaround is to use custom query `FOR e IN company_type FILTER e._key IN @0  RETURN e` but basically this looks like a bug which is not observing the type of incoming data, concret a collection.
Perhaps the reason is the `ArangoExampleConverter:198 ff.` and I did not find any Method representing an `IN` filtering...

It would be great if you can have a look on this issue.

**Comment by rashtao** [comment]
Hi @DevOps-TauRes ,

such method is tested here:
https://github.com/arangodb/spring-data/blob/3b955ae332cccc369a77a2a473d10a22594bc171/src/test/java/com/arangodb/springframework/repository/AbstractTestEntityRepositoryTest.java#L75-L82

From what I can see it generates a multi get request to `PUT /_api/document/{collection}#get` (https://www.arangodb.com/docs/stable/http/document-working-with-documents.html#read-multiple-documents) and not a AQL query.

Can you please provide a snippet to reproduce the issue?

**Comment by rashtao** [comment]
Closing for now, please reopen in case you have further details.
