### ISSUE TITLE
TypeAlias not mapping to correct class when using class inheritance

### ISSUE THREAD

**Issue by reinaldomjr** [arangodb/spring-data#224]
I Mapped a parent class, named "Animal", and two subclasses named, "Cat" and "Dog".

The Animal Class is Abstract and never saved as a document.

Both "Cat" and "Dog" classes have the "@Document("animal")" annotation, so they all save on the same collection.

The subclasses are using @TypeAlias annotation with "Cat" and "Dog" as values, instead of full class name.

When the application is started and I try to list the documents, the lib can't find the reference for TypeAlias, and tries to map the Json to the abstract class "Animal".

The problem does not occur if I add a document for each of the classes BEFORE trying to list them.

Also, this problem do not occur if I don't use @TypeAlias, and rely on the full class name.

A repository with a demonstration is located at:
https://github.com/reinaldomjr/arangodb-springdata-typealias

Steps to reproduce:
1. Build and run the project (connected to an ArangoDB server)
2. populate the base with some data (GET http://localhost:8080/animals/populate)
3. List the documents (GET http://localhost:8080/animals/)
4. Restart the application
5. List the documents Again (GET http://localhost:8080/animals/)
6. Error occurs

**Comment by rashtao** [comment]
Entities classpath scan is performed in the package of `ArangoConfiguration` and recursively in its subpackages, in your case `com.hiveflow.idmmanager.config`, so your domain entities are not discovered.
To fix it you should either:

- manually provide domain entities by overriding `getInitialEntitySet()` in `ArangoDBConfig`, eg.: 
  ```java
    @Override
    public Set<? extends Class<?>> getInitialEntitySet() {
        return Set.of(Animal.class, Dog.class, Cat.class);
    }
  ```

- properly configure domain entities classpath scan by overriding `getEntityBasePackages()` in `ArangoDBConfig`, eg.: 
  ```java
    @Override
    public String[] getEntityBasePackages() {
        return new String[]{"com.hiveflow.idmmanager.domain"};
    }
  ```

- move `ArangoDBConfig` to `com.hiveflow.idmmanager` package

**Comment by rashtao** [comment]
Closing as fixed, please reopen in case of further questions.
