### ISSUE TITLE
Find distinct documents by field name

### ISSUE THREAD

**Issue by alxxyz** [arangodb/spring-data#238]
Is there a way to find distinct documents by a field from the document and not by id as it is by default in derived queries?

**Comment by rashtao** [comment]
This is not supported by Spring Data query derivation. I would recommend you writing your custom AQL query for doing it and use it as argument for @Query annotation. See ref doc here: https://www.arangodb.com/docs/stable/drivers/spring-data-reference-repositories-queries.html#aql-query-options

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
