### ISSUE TITLE
14 bytes too many are persisted per date without time 

### ISSUE THREAD

**Issue by haqer1** [arangodb/spring-data#24]
Type:
java.sql.Date date;
OR
java.time.LocalDate date;

Requested:
this.date = Date.valueOf(LocalDate.now(ZoneOffset.UTC).toString());
OR
this.date = LocalDate.now(ZoneOffset.UTC);
E.g.: 2018-03-29

Persisted, e.g.:
2018-03-29T00:00:00.000Z
Here everything starting with T is really unnecessary: in terms of storage and readability.

P.S.
For java.sql.Date, this also causes retrieval trouble (but this can be worked around by changing to LocalDate):
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.sql.Date] for value '2018-03-29T00:00:00.000Z'; nested exception is java.lang.IllegalArgumentException
	at org.springframework.core.convert.support.ObjectToObjectConverter.convert(ObjectToObjectConverter.java:112)
	at

**Comment by mpv1989** [comment]
changed in 2.1.0
