### ISSUE TITLE
Better java.time support is needed

### ISSUE THREAD

**Issue by haqer1** [arangodb/spring-data#25]
At present:
1. LocalDateTime:
"2018-03-29T17:12:25.756"
persisted as
"2018-03-29T17:12:25.756Z"
2. OffsetDateTime
"2018-03-29T16:28:40.060Z"
persisted as
{"dateTime":"2018-03-29T16:28:40.060Z","offset":"Z"}
3. ZonedDateTime:
"2018-03-29T16:37:06.353Z"
persisted as
{"dateTime":"2018-03-29T16:37:06.353Z","offset":"Z","zone":"Z"}

And retrieval for 2. & 3. is problematic.

IMHO, persisted values should be as in the following examples:
1. "2018-03-29T17:12:25.756"
2. "2018-03-29T16:28:40.060Z", "2018-03-29T23:22:38.116+0N:00"...
3. "2018-03-29T16:37:06.353Z", "2018-03-29T23:22:38.148+0N:00[Continent/City]"
And of course retrieval should be possible for at least 2. (assuming that 3. can be accounted for using 2.).

Until that better future support, it seems there's no choice but to use 1. for now, because (at least for UTC) it kind of looks like 2. would look with better support (but it's a bit confusing, because in Java one would have non-UTC-aware LocalDateTime, which would be persisted essentially as UTC-based OffsetDateTime).

**Comment by haqer1** [comment]
For comparison, here's what PostgreSQL has:
https://jdbc.postgresql.org/documentation/head/8-date-time.html
Essentially, it supports 1. & 2. (but 2. only for UTC). Matching that would probably be a fair target to close this issue.

**Comment by mpv1989** [comment]
changed in 2.1.0
