### ISSUE TITLE
SpEL in @Query annotation is not thread safe

### ISSUE THREAD

**Issue by aburmeis** [arangodb/spring-data#251]
### Problem:
A repository method annotated with `@Query` creates a `StringBasedArangoQuery` which is used for each method call. This implies the reuse of the SpEL `StandardEvaluationContext`, which is created as a final member. Concurrent calls to `AbstractArangoQuery.createQuery()` will propagate different variables derived from `@SpelParam` annotated method parameters to the context in parallel (see `StringBasedArangoQuery.prepareQuery()`) which results in wrong results.

### Fix:
Either make the context usage synchronized (which has performance impacts and is not completely safe due to variables left in the context) or use a own (child) context exposing the SpEL variables from the call:

```java
private String prepareQuery(final ArangoParameterAccessor accessor) {
    synchronized(context) {
        context.setVariables(accessor.getSpelVars());
        String preparedQuery = queryExpression.getValue(context, String.class);
    }
    ...
```

```java
private String prepareQuery(final ArangoParameterAccessor accessor) {
    EvaluationContext childContext = new ChildEvaluationContext(context, accessor.getSpelVars());
    String preparedQuery = queryExpression.getValue(childContext, String.class);
    ...
}

class ChildEvaluationContext extends DelegatingEvaluationContext {
    private final Map<String, Object> additionalVariables;

    ChildEvaluationContext(EvaluationContext delegate, Map<String, Object> additionalVariables) {
        super(delegate);
        this.additionalVariables = additionalVariables;
     }

    @Override
    @Nullable
    public Object lookupVariable(String name) {
        Object value = this.additionalVariables.get(name)
        return value == null ? super. lookupVariable(name) : value;
    }
}
```

(`DelegatingEvaluationContext` is available from spring-security-web und is used here just to clarify the idea. The real solution would need a full implementation)

**Comment by rashtao** [comment]
Thanks for reporting, I suggest fixing this with second approach proposed above.

**Comment by rashtao** [comment]
For the moment, this is fixed in the PR above recreating a new `EvaluationContext` on every `prepareQuery()` invocation. From a first look, this approach should not have performance issues and the code is easier than the decorator above.

**Comment by aburmeis** [comment]
I think this simpler solution is also fine, so there is a o from my side.
