### ISSUE TITLE
how to use collection placeholder？

### ISSUE THREAD

**Issue by woshishitou** [arangodb/spring-data#252]
I try to use collection placeholder in query, but I get error for it.

query:
`@Query("FOR u IN @table FILTER u._key == @rowKey RETURN u")`
`List<Map<String, Object>> getNode(@Param("table") String table, @Param("rowKey") String rowKey);`

error:
`Response: 400, Error: 1563 - AQL: collection or array expected as operand to FOR loop; you specified type 'string' with content '"account"' (while optimizing ast)`

Why this error happen? And How can I user collection placeholder correctly?

**Comment by rashtao** [comment]
Bind parameters identifying a collection should be prefixed by `@`, see https://www.arangodb.com/docs/3.10/aql/fundamentals-bind-parameters.html#collection-bind-parameters

So your code should be:
```
@Query("FOR u IN @@table FILTER u._key == @rowKey RETURN u")
List<Map<String, Object>> getNode(@Param("@table") String table, @Param("rowKey") String rowKey);
```

**Comment by rashtao** [comment]
Closing as inactive, please reopen in case of further questions.

**Comment by woshishitou** [comment]
Thank you very much!
