### ISSUE TITLE
How should I dynamically switch databases

### ISSUE THREAD

**Issue by hejiahuichengxuyuan** [arangodb/spring-data#256]
I use the following code and it doesn't work
```
   @Autowired
    private ArangoOperations arangoOperations;

  @Test
    public void test() {
        ArangoDatabase arangoDatabase = arangoOperations.driver().db(DbName.of("test"));
        ArangoCursor<Map> query = arangoDatabase.query("for p in persons return p", Map.class);
        System.out.println(query.getCount());
    }
```

```
<dependency>
      <groupId>com.arangodb</groupId>
      <artifactId>arangodb-spring-boot-starter</artifactId>
      <version>2.6-0</version>
 </dependency>
```

**Comment by rashtao** [comment]
Database name field supports SPEL expressions. You can find an example here:
- https://github.com/arangodb/spring-data/blob/fce2e77275949670e63c93d0f3c4546ee3091d6f/src/test/java/com/arangodb/springframework/ArangoMultiTenancyTestConfiguration.java#L52
- https://github.com/arangodb/spring-data/blob/df545096e1d478557858327c3420c08da6c65b06/src/test/java/com/arangodb/springframework/core/mapping/MultiTenancyDBLevelMappingTest.java#L58-L83
- https://github.com/arangodb/spring-data/blob/176f5da7eb9d4e457f9ea915f97632f8d3b80503/src/test/java/com/arangodb/springframework/component/TenantProvider.java

**Comment by hejiahuichengxuyuan** [comment]
I tried it except query doesn't work,  

```
 @Test
    public void test() {

        {
            tenantProvider.setId(TESTDB);
            ArangoDatabase db = arangoOperations.driver().db(TESTDB);
            System.out.println("db.getGraphs().size() = " + db.getGraphs().size());
            db.collection("test2").drop(); // ok
            
            ArangoCursor<Map> query = db.query("for p in persons return p", Map.class);
            System.out.println(query.getCount()); // null
        }
    }
```

**Comment by rashtao** [comment]
To return the count from an AQL query you need to specify `count(true)` in the AQL options, see https://github.com/arangodb/arangodb-java-driver/blob/62b2d60372e3a1b552864664a99ec932d58f2436/src/test/java/com/arangodb/ArangoDatabaseTest.java#L597-L610

**Comment by hejiahuichengxuyuan** [comment]
Thanks for your help I made it
