### ISSUE TITLE
[DE-682] unify exception handling

### ISSUE THREAD

**Issue by aburmeis** [arangodb/spring-data#281]
Currently Arango Spring Data handles `ArangoDBException` using `ArangoExceptionTranslator` for most methods of `ArangoOperations` except the `query()` ones. This is not handy and not what a user would expect from a Spring Data implementation as all queries (derived queries and those using `@Query` annotation) end up in a query call throwing `ArangoDBException` instead of the expected `DataAccessException`.

So even `query()` should use exception translation and maybe `ArangoExceptionTranslator` could be improved using error numbers to translate exceptions more specific.

**Comment by rashtao** [comment]
In https://github.com/arangodb/spring-data/commit/ba4a37f0954fe8437a751ded7767af0c0cda1f43 I reverted your changes to translate via `ArangoExceptionTranslator` exceptions in  `ArangoOperations.query()`.

**Comment by aburmeis** [comment]
@rashtao thanks, so this ist mostly a better exception translation
