### ISSUE TITLE
com.arangodb.ArangoDBException: Response: 400, Error: 1553 - bind parameter '@col' has an invalid value or type

### ISSUE THREAD

**Issue by bobaikato** [arangodb/spring-data#290]
We have a simple PhoneNumber model which uses the Phone Number as the Key.
On creating a new Phone Number we are getting this error
```
com.arangodb.ArangoDBException: Response: 400, Error: 1553 - bind parameter '@col' has an invalid value or type
```

So we've noticed something strange to us, unsure if you'd find it strange.

When we switched to using the `HTTP2_VPACK` protocol, the error started. Not that we've reverted to `HTTP2_JSON` things started working fine.

**Comment by rashtao** [comment]
Thanks for reporting this, to better figure out where the problem lies, can you provide a code snippet to reproduce the problem? In particular I would be interested in the following details:
- code of the PhoneNumber class
- template or repository method causing the issue
- relevant stack trace of the exception
- debug logs of the request and response causing the exception (debug level logs of `com.arangodb.http.HttpCommunication`)

**Comment by rashtao** [comment]
Sorry, no need to provide the info above, I could reproduce the issue and going to look into it.

**Comment by bobaikato** [comment]
Thank you for implementing the solution. When can we expect the changes to be released?

**Comment by rashtao** [comment]
Released in https://github.com/arangodb/spring-data/releases/tag/v4.1.0

**Comment by rashtao** [comment]
Also please note that when using VPACK content-type, the method `ArangoConfiguration#contentType()` must be overridden to return `ContentType.VPACK`, see https://docs.arangodb.com/stable/develop/integrations/spring-data-arangodb/#configuration

**Comment by bobaikato** [comment]
Is it really necessary to have the user perform that task? Instead, you could incorporate that condition within the builder for Content-Type VPACK, specifically when the Protocol is set to the same

I will open a PR for that.

**Comment by bobaikato** [comment]
it appears that ArangoDB doesn't expose the configuration fields. The design could be improved, to be honest. If the Protocol is VPACK, it inherently implies the content type. Is there really a need for the user to specify the content type in such cases?

**Comment by rashtao** [comment]
Yes, for the moment you need to specify it. Implementing it in other ways would have caused API breaking changes in `ArangoConfiguration`.
In the next major release we can improve it inferring the content-type directly from configured protocol.

**Comment by bobaikato** [comment]
Upon revisiting the issue, I observed that attempting to override the `ContentType` method to `VPACK` resulted in an error, specifically, "No JsonFactory found for content type: VPACK." Further investigation led me to scrutinize the code responsible for creating the `ObjectMapper`. In particular, I focused on the section where the `formatName` is assigned based on the provided `ContentType`.

In the code snippet below, when the `ContentType` is set as `VPACK`, the `formatName` is assigned as "Velocypack." The subsequent check, however, compares this `formatName` with the result of `jf.getFormatName()`. The `getFormatName()` method, when invoked on the `JsonFactory` class, returns "JSON" or `null`. In the case of `VPACK`, it returns `null`.

```java
public String getFormatName() {
    return this.getClass() == JsonFactory.class ? "JSON" : null;
}
```

As a consequence, the condition `if (formatName.equals(jf.getFormatName()))` fails, causing the loop to terminate prematurely. Consequently, the process proceeds to throw the exception below:

```java
throw new ArangoDBException("No JsonFactory found for content type: " + contentType);
```

The comparison between "Velocypack" and `null` prevents the expected behaviour, leading to the mentioned exception.

Consider revising the comparison logic and let me know.


Exact code.
```java
    public static ObjectMapper of(ContentType contentType) {
        String formatName;
        if (contentType == ContentType.JSON) {
            formatName = "JSON";
        } else {
            if (contentType != ContentType.VPACK) {
                throw new IllegalArgumentException("Unexpected value: " + contentType);
            }
            formatName = "Velocypack";
        }

        ServiceLoader<JsonFactory> sl = ServiceLoader.load(JsonFactory.class);
        Iterator var3 = sl.iterator();

        while(var3.hasNext()) {
            JsonFactory jf = (JsonFactory)var3.next();
            if (formatName.equals(jf.getFormatName())) {
                if (contentType == ContentType.JSON) {
                    JacksonUtils.tryConfigureJsonFactory(jf);
                }

                return new ObjectMapper(jf);
            }
            LOG.debug("Required format ({}) not supported by JsonFactory: {}", formatName, jf.getClass().getName());
        }
        throw new ArangoDBException("No JsonFactory found for content type: " + contentType);
    }
```

**Comment by rashtao** [comment]
In order to use `VPACK` content type, you need to include `com.arangodb:jackson-serde-vpack`, see https://docs.arangodb.com/3.11/develop/drivers/java/reference-version-7/changes-in-version-7/#modules. 
This provides a `JsonFactory` implementation that overrides `getFormatName()`.
