### ISSUE TITLE
CRUD Repository save and saveAll should return fetched entity instead of original

### ISSUE THREAD

**Issue by aburmeis** [arangodb/spring-data#291]
If you want to use any relations included by annotated members, currently an additional fetch is needed as the original saved entity typically has no proxies for relations or refs.

This is also a very typical behaviour of other spring data implementations. Not sure if this is a bug or an enhancement.

The code involved are the default implementations in `SimpleArangoRepository` which currently does an explicit return of the original entity instead of returning the `REPSERT` result in `save()` and `saveAll()`.

**Comment by rashtao** [comment]
Is there any convention about it in Spring Data NoSQL projects?
AFAICS in Spring Data MongoDB, `CrudRepository#save(S): S` returns:
- the same instance as the argument, optionally populated with new values, if the argument is mutable
- a new instance, if the argument is immutable (e.g. Java record)
