### ISSUE TITLE
To and From annotation not serializing when overriding serde in ArangoConfiguration

### ISSUE THREAD

**Issue by mckernant1** [arangodb/spring-data#304]
## Versions
Spring plugin: 3.2.3
Spring Dep management plugin: 1.1.4
arangodb-spring-boot-starter: 3.2-0

## Code
I have sampled this out to a small repo here: https://github.com/mckernant1/arango-annotation-issue

## Problem

When I override the serde method in ArangoConfiguration, and try to insert an edge with ArangoOperations.insert
```java
@Override
public ArangoSerde serde() throws Exception {
    return JacksonSerde.of(ContentType.JSON);
}
```

I see this error
```
com.arangodb.ArangoDBException: Response: 400, Error: 1233 - expecting both `_from` and `_to` attributes to be defined in the edge document and have the format `<collectionName>/<vertexKey>`
```

**Comment by rashtao** [comment]
Spring Data mapping logic is implemented by `ArangoConverter`. `ArangoSerde` delegates the mapping to it, see:

https://github.com/arangodb/spring-data/blob/main/src/main/java/com/arangodb/springframework/config/ArangoConfiguration.java#L99 

and 

https://github.com/arangodb/spring-data/blob/main/src/main/java/com/arangodb/springframework/config/ArangoConfiguration.java#L108

You should either delegate the mapping to `ArangoConverter` or implement your own mapping logic.

**Comment by mckernant1** [comment]
I see. So if you want to add jackson modules you need to redefine this object https://github.com/arangodb/spring-data/blob/main/src/main/java/com/arangodb/springframework/config/ArangoConfiguration.java#L92.

Ok Thank you

**Comment by rashtao** [comment]
Alternatively you can register reading/writing converters from/to `JsonNode` by overriding `ArangoConfiguration#customConverters()` , see https://docs.arangodb.com/stable/develop/integrations/spring-data-arangodb/reference-version-4/mapping/converter/.
