### ISSUE TITLE
[DE-816] Support spring boot 3.3.0

### ISSUE THREAD

**Issue by AnnieSemenova** [arangodb/spring-data#305]
Hello! 
We faced a problem during spring boot upgrade. We found out that deprecated method is used in class ArangoQueryMethod, please see:

https://github.com/arangodb/spring-data/blob/main/src/main/java/com/arangodb/springframework/repository/query/ArangoQueryMethod.java#L68

It was marked as deprecated since 3.1:
https://docs.spring.io/spring-data/commons/docs/3.2.5/api/org/springframework/data/repository/query/QueryMethod.html#createParameters(java.lang.reflect.Method)

In the latest version it was removed at all:
https://docs.spring.io/spring-data/commons/docs/3.3.0/api/org/springframework/data/repository/query/QueryMethod.html

Could you support 3.3.0 version? 

Thank you!

**Comment by baniakjr** [comment]
Hi, I faced the same issue. I've uploaded my patch, seems to work fine after changes. Maybe it will help in supporting spring boot 3.3.0

pull request #306

**Comment by rashtao** [comment]
Thanks for reporting, PR https://github.com/arangodb/spring-data/pull/306 has been merged (but not released yet).
https://github.com/arangodb/spring-boot-starter will also be updated accordingly.

**Comment by rashtao** [comment]
https://github.com/arangodb/spring-boot-starter/commit/8bc12059a92a86c1f538263c851502ce5e71d638

**Comment by rashtao** [comment]
released in https://github.com/arangodb/spring-data/releases/tag/v4.2.0
