### ISSUE TITLE
4.3.0 ArangoTemplate autowire

### ISSUE THREAD

**Issue by baniakjr** [arangodb/spring-data#318]
Hi,

I've got a problem after upgrading to version 4.3.0

I'm getting error on intialization:
`Parameter 0 of method setArangoTemplate in com.arangodb.springframework.repository.ArangoRepositoryFactoryBean required a bean of type 'com.arangodb.springframework.core.template.ArangoTemplate' that could not be found.`

Seems like ArangoOperatin in ArangoRepositoryFactoryBean was change to ArangoTemplate:
https://github.com/arangodb/spring-data/blob/645e33c503bccb40a19bc19ac1cd00920f5c3bfc/src/main/java/com/arangodb/springframework/repository/ArangoRepositoryFactoryBean.java#L49-L52 
However in  ArangoConfiguration there's bean factory only for ArangoOperation: https://github.com/arangodb/spring-data/blob/645e33c503bccb40a19bc19ac1cd00920f5c3bfc/src/main/java/com/arangodb/springframework/config/ArangoConfiguration.java#L85-L88 which in fact is returning ArangoTemplate, however spring is not finding it as a proper candidate.

I've created PR #319 with simple solution. However haven't got time to test it extensively yet.
I've only check that my app using it is initializing properly, passing tests and performing basic db operation without problems.

**Comment by rashtao** [comment]
Merged, thank you!
