### ISSUE TITLE
Handling of java.time in converters

### ISSUE THREAD

**Issue by christian-lechner** [arangodb/spring-data#36]
Hello @mpv1989,

I'm just looking at the `TimeStringConverters` and `JodaTimeStringConverters` and I see that you are using the `java.util.Date` there and the `DateUtil `with the not thread-safe `SimpleDateFormat` (I saw your trick with `ThreadLocal ` ;)).

I think we should move to the new and thread-safe `DateTimeFormatter` and leave `java.util.Date` and `SimpleDateFormat` behind.

The next thing we should think about is how we serialize the `LocalDateTime` and `LocalDate`. I saw that you are converting it to UTC in `TimeStringConverters`, but not in `JodaTimeStringConverters`.

As `LocalDateTime` and `LocalDate` are explicitly local (= without timezone) we should maybe keep it as it is (since we don't know if really the system default is used). If the user really wants UTC, he could use `LocalDateTime.now(ZoneOffset.UTC)` or `Instant`, which is UTC by definition.

I'm not sure if the auto-conversion is what users want. I saw a user complaining about it on SO for mongo java driver.

How about this conversions:

 Class  | Format  
 :--- | :---
 `java.util.Date` | `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`
 `LocalDate` | `yyyy-MM-dd`
 `LocalDateTime` | `yyyy-MM-dd'T'HH:mm:ss.SSS`
 `Instant` | `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`
 `OffsetDateTime` | `yyyy-MM-dd'T'HH:mm:ss.SSSXXX`

This would also address issues #24 and #25.

**Comment by mpv1989** [comment]
@christian-lechner I agree.

I would recommend to let the `DateUtil` in [arangodb/java-velocypack](https://github.com/arangodb/java-velocypack) as it is. We have the requirement that this module remains Java 6 compatible. We should implement a new util class in [arangodb/java-velocypack-module-jdk8](https://github.com/arangodb/java-velocypack-module-jdk8) and also use it there for the serializers/deserializers and here. I would like to keep the behavior of the driver and spring data module equal.

What do you think?

**Comment by christian-lechner** [comment]
Of course we should leave the `DateUtil` as it is. The `SimpleDateFormat `is anyway the best way to deal with `Date `objects.

I meant that we should change the `TimeStringConverters`. Please see this [gist ](https://gist.github.com/christian-lechner/4152974a9ad050725c42e0b21250cd7e)how it could look like.

**Comment by christian-lechner** [comment]
I propose the following serialization formats:

Class  | Format  
 :--- | :---
 `LocalDate` | `DateTimeFormatter.ISO_LOCAL_DATE`
 `LocalDateTime` | `DateTimeFormatter.ISO_LOCAL_DATE_TIME`
 `Instant` | `DateTimeFormatter.ISO_INSTANT`
 `OffsetDateTime` | `DateTimeFormatter.ISO_OFFSET_DATE_TIME`
`ZonedDateTime `| `DateTimeFormatter.ISO_ZONED_DATE_TIME`

**Comment by mpv1989** [comment]
Hi @christian-lechner,

I changed the serialization of all mentioned classes in [arangodb/java-velocypack-module-jdk8](https://github.com/arangodb/java-velocypack-module-jdk8/commit/014c07cb736aea6b2b0fd99fbea51fa9efccf411). I will release a new version of this module today and then we can use the `JavaTimeUtil` in `TimeStringConverters`. 

It may be a little exaggerated to implement a util, but I want to make sure that the same logic is used in both modules.

**Comment by christian-lechner** [comment]
Nothing wrong with your util, especially if there are changes to be made :)

The `java.time.*` classes can be added to the `ArangoSimpleTypes` I created. All classes in there are handed to the velocypack serializer. Then we would only need the deserializers from `String`. It could be that they are already handled by the `DefaultConversionService`.

Let me know if I should help you with a PR or so.

**Comment by christian-lechner** [comment]
The `java-velocypack-module-joda` should also be updated.

**Comment by mpv1989** [comment]
@christian-lechner I pushed the changes in `TimeStringConverters` (see [commit](https://github.com/arangodb/spring-data/commit/067b5fd8e683f10604b40bcccaa687ce949cdc72)).

In terms of `java-velocypack-module-joda`, I don't know if I want to use `DateTimeFormatter` since the module is currently compatible with Java 6 and I am not sure if it is a good idea to drop this.

**Comment by christian-lechner** [comment]
You should keep the Java 6 compatibility ;)

But the `java-velocypack-module-joda` is now behaving differently than the `java-velocypack-module-jdk8` (serialization of `LocalDateTime` and `LocalDate`).

The `JodaTimeStringConverters` in this project can be adapted to the new serialization format from (that format from `java.time`).

**Comment by christian-lechner** [comment]
You can keep the Java 6 compatibility as Joda Time is compatible with Java 5.

The `java-velocypack-module-joda` is now behaving differently than the `java-velocypack-module-jdk8` (serialization of `LocalDateTime` and `LocalDate`).

The `JodaTimeStringConverters` in this project should be adapted to the new serialization format (the format from `TimeStringConverters`) or removed as for Java 8 we have `java.time` which is essentially the same.

**Comment by christian-lechner** [comment]
@mpv1989 you wrote:

>In terms of `java-velocypack-module-joda`, I don't know if I want to use `DateTimeFormatter `since the module is currently compatible with Java 6 and I am not sure if it is a good idea to drop this.

As Joda Time and `java.time` are different libraries you can't even use `DateTimeFormatter `of `java.time` for Joda Time. To make it clear:

> The standard date and time classes prior to Java SE 8 are poor. By tackling this problem head-on, Joda-Time became the de facto standard date and time library for Java prior to Java SE 8. **Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project.** [source](http://www.joda.org/joda-time/)

So you need to use formatter and parser from Joda Time and thus you stay Java 6 compatible. I've created a Gist for you that shows how you could do it: [JodaTimeUtil.java](https://gist.github.com/christian-lechner/88c1997558b541238e7f1d9af959e9af).

Joda Time's formatters and parsers behave a little different than the one from `java.time`, but that shouldn't be an issue.

**Comment by mpv1989** [comment]
@christian-lechner Thanks for your Gist. Just a little note. I had to change one method
```Java
public static DateTime parseDateTime(final String source) {
  return DateTime.parse(source, ISODateTimeFormat.dateTime());
}
```
Without the parameter `ISODateTimeFormat.dateTime()` the timezone is not parsed correct. You can't see this in the saved document or when you call `toString()` on an deserialized object but when you call `equal()` against the original you see that they are not equal.

**Comment by mpv1989** [comment]
Just released 2.1.0. Thanks again for your contribution

**Comment by christian-lechner** [comment]
@mpv1989 I think you made a mistake here.

`DateTime.parse(String)` uses `ISODateTimeFormat.dateTimeParser().withOffsetParsed()` internally. The `withOffsetParsed()` means that (if there is an offset) it is parsed and stored in the `DateTime `object.

If you use the constructor `new DateTime(source)` or `DateTime.parse(source, ISODateTimeFormat.dateTime())`, the offset is set to the system default. If you create and parse the `DateTime `object on the same machine (as your tests) then you can't see the difference. But if you parse a string from a different time zone, you'll indeed see the difference:

```java
String source = "2018-04-20T12:15:44.094+05:00";
DateTime.parse(source); // returns 2018-04-20T12:15:44.094+05:00
DateTime.parse(source, ISODateTimeFormat.dateTime()); // returns 2018-04-20T09:15:44.094+02:00
new DateTime(source); // returns 2018-04-20T09:15:44.094+02:00
```

The last two are still correct as they modify the time accordingly when switching the offset to the system default. But I think `DateTime.parse(source)` is the one we should use, as it directly reflects the parsed string.

I've seen that you use the constructor of `DateTime`, that's why your tests failed with `equals`.

**Comment by mpv1989** [comment]
@christian-lechner Ok, that makes total sense. Thanks, I will fix this and release a new patch version
