### ISSUE TITLE
After migration on the latest version (2.1.0) unable to deserialize enums

### ISSUE THREAD

**Issue by mxmind** [arangodb/spring-data#39]
We used the spring-data library with a bit old version (2.0.1) everything was ok. But a few days ago after migration to the latest stable version we faced very strange behavior with the serialization of enums.
Just, for example, user status enum is:
```java
public enum UserStatus {
    VERIFIED("Verified"), PENDING("Pending"), BANNED("Banned");

    @Getter
    @JsonValue
    private final String status;

    UserStatus(String status) {
        this.status = status;
    }

    @JsonCreator
    public static UserStatus findValue(String status) {
        return Stream.of(UserStatus.values())
            .filter(value -> value.status.equals(status))
            .findFirst()
            .orElseThrow(() -> new IllegalStateException(String.format("UserStatus do not have such value: %s", status)));
    }
}
```
Previously, it was saved in database as string, but now saved as following structure:
```json
"status": {
    "name": "PENDING",
    "status": "Pending",
    "ordinal": 1
  }
```

Could you add proper serialization of enums? 

P.S. Fixed by adding custom converters. But would be great to have default converter for enums

**Comment by mpv1989** [comment]
Hi @mxmind,

thanks for reporting. I released bug-fix release `2.1.2`

best
Mark
