### ISSUE TITLE
Optimize/fix data-pollution/disk-space-waste, memory, bandwidth, CPU & money waste, as well as avoid visual clutter & tight-coupling between DB & Java (that was introduced last week)

### ISSUE THREAD

**Issue by haqer1** [arangodb/spring-data#40]
PR #33 introduced data pollution for mainstream inheritance types like TABLE/COLLECTION per ENTITY/DOCUMENT. For TABLE/COLLECTION_PER_CLASS type inheritance there is already an entire 
TABLE/COLLECTION dedicated for the class involved, so there's no need to store anything type-related as a property/column (let alone the fully-qualified class name).

**Comment by christian-lechner** [comment]
This issue doesn't make any sense, as there is no COLLECTION_PER_CLASS inheritance in this project.

**Comment by haqer1** [comment]
> This issue doesn't make any sense, as there is no COLLECTION_PER_CLASS inheritance in this project.
False.

For the (apparently) unenlightened:
COLLECTION_PER_CLASS: means when there are 2+ documents/entities one extending another (& when EACH of them is marked as @ Document), each one is stored in a separate collection (in SQL jargon: table). This is extactly how ArangoDB works (as also stated in the original issue: https://github.com/arangodb/spring-data/issues/17#issue-304481714): again, claiming otherwise is insane or egregious kind of lying (like claiming that white is black). Anybody reading who is in doubt, can just try persisting PersonSuperclass & DeveloperSubclass from
https://github.com/haqer1/spring-data/blob/master/src/test/java/com/arangodb/springframework/core/convert/InheritanceSupportTest.java
(without including the rest of rational/optimizing code), & you will see that the classes get stored in 2 different collections: namely, COLLECTION_PER_CLASS.
SINGLE_COLLECTION: means when there are 2+ documents/entities one extending another (& when EACH of them is marked as @ Document), all are stored in the same collection. This is not how ArangoDB works, & thus ArangoDB doesn't currently support this type of inheritance mapping.
JOINED_COLLECTION: means when there are 2+ documents/entities one extending another (& when EACH of them is marked as @ Document), the data shared with the parent class of all relevant classes is stored in the parent collection, & the additional data for the others is stored in additional collections with the resulting mapping involving a join of the shared data & the non-shared data. ArangoDB's mapping libraries currently do not have this type of flexibility at all.
