### ISSUE TITLE
ArangoCursor support in repository query methods

### ISSUE THREAD

**Issue by christian-lechner** [arangodb/spring-data#47]
This is a follow-up issue of #46 and [DATACMNS-1323](https://jira.spring.io/browse/DATACMNS-1323).

Oliver Gierke thinks that something like a cursor should not be used in client repository code. Any opinions on this?

If it should be further supported, we can't just override `QueryMethod.getReturnedObjectType()` as this leads to a NPE. @mpv1989 added the workaround from #46.

The "Spring Data way", as pointed out by Oliver Gierke, is to override the `RepositoryMetadata.getReturnedDomainClass()` in a custom class and return it from `ArangoRepositoryFactory.getRepositoryMetadata()`.

According to Oliver Gierke the `QueryMethod.getReturnedObjectType()` is "some kind of left-over from the pre-ResultProcessor days". Therefore, we should also use the result processor, which can also be used for projections.

Any comments? ;)

**Comment by christian-lechner** [comment]
I implemented Oliver Gierke's suggestion and it works as expected: [ArangoRepositoryFactory](https://github.com/christian-lechner/spring-data/blob/cursor_support/src/main/java/com/arangodb/springframework/repository/ArangoRepositoryFactory.java).

**Comment by mpv1989** [comment]
@christian-lechner Cool. I would like to support ArangoCursor. As you have already written in the ticket, you can get back more information and these could be also improved in the future.

**Comment by christian-lechner** [comment]
@mpv1989 If you like, I can submit a PR next week that makes use of the Spring Data `ResultProcessor` to obtain the correct type and to support projections.

**Comment by christian-lechner** [comment]
@mpv1989 I created PR #49.

**Comment by mpv1989** [comment]
@christian-lechner PR merged, thank you
