### ISSUE TITLE
Pagging With Pageable is not work

### ISSUE THREAD

**Issue by adipurapunya** [arangodb/spring-data#50]
I have custom query with only few field in RETURN like this

@Query("FOR person IN persons RETURN {id : person._id, name : person.name, username : person.username, email : person.email, profilFacebookId: person.profilFacebookId, gender : person.gender}") 
Page  `<` PersonWithoutLinkPhotos `>` findAllPersonsWithoutLinkPhotos(Pageable arg0);

My Controller 
final Pageable pageable = PageRequest.of(0, 5);

Page `<` PersonWithoutLinkPhotos `>` data = personRepository.findAllPersonsWithoutLinkPhotos(pageable);

**the result is still show all data.**

Person Class
@Document("persons")
@HashIndex(fields = { "profilFacebookId", "username", "email" }, unique = true)
public class Person {
	@Id
	private String id;
	private String name;
	private String username;
	private String email;
	private String profilFacebookId;
	private String gender;
	private List<String> linkPhotos;
	private List<String> linkPhotosCloud;
	private boolean alive;
	private Integer age;
	@Relations(edges = ChildOf.class, lazy = true)
	private Collection<Person> childs;
        // getter setter
}

PersonWithoutLinkPhotos Class // My custom for handle result.

public class PersonWithoutLinkPhotos {
	private String id;
	private String name;
	private String username;
	private String email;
	private String profilFacebookId;	
	private String gender;
        // getter setter
}

I used 
spring boot 2.0.2.RELEASE
arangodb-spring-data 2.1.3
Db : ArangoDB Enterprise Edition 3.3.8 and 3.3.9.

**Comment by mpv1989** [comment]
@adipurapunya I just release version `2.1.4` and `1.1.3` which supports paging and sorting for native queries. Take a look into the [docs](https://github.com/arangodb/spring-data/blob/master/docs/Drivers/SpringData/Reference/README.md#paging-and-sorting) how to use it.

**Comment by adipurapunya** [comment]
I have tried version 2.1.4 and success.
But, when I build my spring boot project as war and deploy in server production by using apache-tomcat-8.5.14, that is error like this:

> Message Response: 400, Error: 1501 - AQL: syntax error, unexpected $undefined near '#pageable RETURN {id : person._i...' at position 1:23 (while parsing)

**Comment by christian-lechner** [comment]
@adipurapunya I packaged a simple Spring Boot application that uses the new paging feature of native queries into a WAR and deployed it under Tomcat 8.5. It worked for me. Have you used an old version of Spring Data ArangoDB to build your WAR?

**Comment by christian-lechner** [comment]
@adipurapunya Look [here](https://github.com/christian-lechner/movie-platform-test) to see how to do it. To build the WAR do `mvn clean package`.

**Comment by adipurapunya** [comment]
Ok. I will try that. let me try .....
