### ISSUE TITLE
Fetch Data By Field filtering is not work

### ISSUE THREAD

**Issue by adipurapunya** [arangodb/spring-data#52]
My Person Repository :
Iterable<Person> findByName(String name);

when I fetch data using native query or findByName query with Filter one column is always error like this

java.time.format.DateTimeParseException: Text 'dewi' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949) ~[na:1.8.0_172]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[na:1.8.0_172]
	at java.time.Instant.parse(Instant.java:395) ~[na:1.8.0_172]

and soo on.....

"dewi" is the parameter name that i input.

I used
spring boot 2.0.2.RELEASE
arangodb-spring-data 2.1.3
Db : ArangoDB Enterprise Edition 3.3.8 and 3.3.9.

**Comment by christian-lechner** [comment]
Please use Spring Boot 2.0.1.RELEASE. There was a change in Spring Data with the 2.0.2.RELEASE that keeps Spring Data ArangoDB 2.1.3 from working correctly. This will be fixed in the next release of Spring Data ArangoDB.
