### ISSUE TITLE
Like Expression with '%param%' does not work in custom query 

### ISSUE THREAD

**Issue by adipurapunya** [arangodb/spring-data#53]
My Repository

```
@Query("FOR person IN persons FILTER LIKE(LOWER(person.name), '%LOWER(@name)%') RETURN {id : person._id, name : person.name, username : person.username, email : person.email, profilFacebookId: person.profilFacebookId, gender : person.gender}")
	PersonWithoutLinkPhotos findByNameFB(@Param("name") String name);
```

always return error like this
 
`com.arangodb.ArangoDBException: Response: 400, Error: 1552 - AQL: bind parameter 'name' was not declared in the query (while parsing) at com.arangodb.internal.util.ResponseUtils.checkError(ResponseUtils.java:53) ~[arangodb-java-driver-4.4.0.jar:na] at com.arangodb.internal.velocystream.VstCommunication.checkError(VstCommunication.java:116) ~[arangodb-java-driver-4.4.0.jar:na]`

but if i change to **LIKE(LOWER(person.name), LOWER(@name))** it's work but does not match that i want. i have to write full name to make it work's. 

I used
spring boot 2.0.1.RELEASE
arangodb-spring-data 2.1.3
Db : ArangoDB Enterprise Edition 3.3.8 and 3.3.9.

**Comment by positiveneutron** [comment]
I'm newbie at JAVA. I have some problem too, I believe that is about typing rules.

**Comment by nurmanhariyanto** [comment]
I have same problem too, need a solution :)

**Comment by christian-lechner** [comment]
You have two possibilities:

1. Create the like expression in Java:
```java
@Query("FOR person IN persons FILTER LOWER(person.name) LIKE @name RETURN {id : person._id, name : person.name, username : person.username, email : person.email, profilFacebookId: person.profilFacebookId, gender : person.gender}")
PersonWithoutLinkPhotos findByNameFB(@Param("name") String name);

final String name = "SomeName";
final String likeExpr = "%" + name.toLowerCase() + "%";
findByNameFB(likeExpr);
```

2. Use AQL:
In order to concatenate `%` with a bind parameter you need to use `CONCAT` function.
```java
@Query("FOR person IN persons FILTER LOWER(person.name) LIKE CONCAT('%', LOWER(@name), '%') RETURN {id : person._id, name : person.name, username : person.username, email : person.email, profilFacebookId: person.profilFacebookId, gender : person.gender}")
PersonWithoutLinkPhotos findByNameFB(@Param("name") String name);

final String name = "SomeName";
findByNameFB(name);
```

**Comment by adipurapunya** [comment]
Ok. Thank you. everything is works ..... 👍
