### ISSUE TITLE
you don't have any query lookup strategy defined

### ISSUE THREAD

**Issue by Sinisterish** [arangodb/spring-data#54]
i get "You have defined query method in the repository but you don't have any query lookup strategy defined. The infrastructure apparently does not support query methods!"
when trying to run a springboot app with arango repository containing @query 
`public interface TraversalRepository extends ArangoRepository<BaseDocument>{
@Query(value="FOR vcenter IN PV return vcenter")
	Iterable<BaseDocument> listPVs();	
}
`
using spring boot version 2.1.0.BUILD-SNAPSHOT
and arango spring data 2.1.3
`<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
		    <groupId>com.arangodb</groupId>
		    <artifactId>arangodb-spring-data</artifactId>
		    <version>2.1.3</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>`

any suggestions?

**Comment by christian-lechner** [comment]
Have you changed the `EnableArangoRepositories.queryLookupStrategy()`? Can you try to use the latest stable version of Spring Boot (2.0.2.RELEASE)?

**Comment by christian-lechner** [comment]
Interesting. The `pom.xml` of Spring Data ArangoDB already includes this dependency.

**Comment by mpv1989** [comment]
@christian-lechner but when you use 
```
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>2.1.0.BUILD-SNAPSHOT</version>
</parent>
```
it gets overwritten with spring-data-commons 2.1.0.M3, which looks like is not compatible with Spring Boot 2.1.0.

@Sinisterish as @christian-lechner already said, it is highly recommended to use Spring Boot 2.0.2.RELEASE

**Comment by mpv1989** [comment]
I'm assuming the problem does not exists anymore. I'll close this issue, feel free to open it again if the problem still persists
