### ISSUE TITLE
java.lang.String converted to java.time.Instant

### ISSUE THREAD

**Issue by bthj-tms** [arangodb/spring-data#55]
When saving a simple Java bean (Character from the demo) I'm getting the error:

```
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.time.Instant] for value ...
```

where the value is from a String property (name), containing nothing resembling  a date.

Debugging this I see that in the method `getOrCreateAndCache` in `com.arangodb.springframework.core.convert.CustomConversions` calls `producer.get()`  which has the property `sourceType.name` set to "java.lang.String" but returns the type "java.time.Instant".

I'm stuck with Spring Boot 1.5.13.RELEASE, as I'm waiting for Apache Camel to support v2, and so I'm using version 1.1.2 of arangodb-spring-data.

Any ideas what may be causing this problem?

**Comment by christian-lechner** [comment]
This issue is already fixed with Spring Data ArangoDB 1.1.3.

**Comment by bthj-tms** [comment]
Thanks, that version indeed fixed the problem :)

I didn't see that version at
https://mvnrepository.com/artifact/com.arangodb/arangodb-spring-data
- is there a better source to watch new releases?

**Comment by bthj-tms** [comment]
...I see the version at https://search.maven.org so I guess that site is a better option.

**Comment by christian-lechner** [comment]
The best source is, of course, the official [Maven Central Repository](https://repo.maven.apache.org/maven2/). The Central Repository gets its data from a few other repositories. It's updated every few hours or so.

One of them is [OSS Sonatype](https://oss.sonatype.org/content/repositories/) which is used by this project here. As data is directly uploaded to this repository, it's also the most up-to-date repository.

Other sites may be significantly out of date.

Links:
- [Spring Data ArangoDB releases in the Central Repository](https://repo.maven.apache.org/maven2/com/arangodb/arangodb-spring-data/)
- [Spring Data ArangoDB releases in the OSS Sonatype repository](https://oss.sonatype.org/content/repositories/releases/com/arangodb/arangodb-spring-data/)
