### ISSUE TITLE
Fix incorrect equality comparison in AbstractArangoQuery.execute (& associated compiler warning)

### ISSUE THREAD

**Issue by haqer1** [arangodb/spring-data#64]
`GeoPage.class.equals(method.getReturnType())`
is meaningless & is always false.

P.S. Compiler warning:
Unlikely argument type for equals(): TypeInformation<capture#3-of ?> seems to be unrelated to Class<GeoPage>

**Comment by mpv1989** [comment]
Thanks for reporting. I pushed a fix.
