### ISSUE TITLE
Don't forget to tag releases & push (release) tags: 2.1.7 not properly tagged on github

### ISSUE THREAD

**Issue by haqer1** [arangodb/spring-data#73]
`ikincil-dev@ziya-u16:~/development/projects/tiers/arangodb/truth/head/spring-data$ head -n 10 pom.xml | grep version`
	<version>2.1.7</version>
`ikincil-dev@ziya-u16:~/development/projects/tiers/arangodb/truth/head/spring-data$ git tag | tail -n 5`
2.1.2
2.1.3
2.1.4
2.1.5
2.1.6
`ikincil-dev@ziya-u16:~/development/projects/tiers/arangodb/truth/head/spring-data$ `

**Comment by christian-lechner** [comment]
The tag will be added when it's released to Sonatype.

**Comment by mpv1989** [comment]
I was not able to release yesterday. Release is now done and tags are also created
