### ISSUE TITLE
Feature: support of all spring data annotations

### ISSUE THREAD

**Issue by mpv1989** [arangodb/spring-data#77]
https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/annotation/package-summary.html

**Comment by christian-lechner** [comment]
This feature request should be complete with PR #118. There is only one annotation left that is not supported: `@Version`. But since the docs state:
> Demarcates a property to be used as version field to implement optimistic locking on entities.

So, we can't implement `@Version` since optimistic locking is not supported by ArangoDB.
