### ISSUE TITLE
Feature: change @Id to save _key instead of _id

### ISSUE THREAD

**Issue by mpv1989** [arangodb/spring-data#78]
Currently a field annotated with `@Id` is saved as `_id` in ArangoDB. Since this field is more for internal usage and does not offer any benefit to the user, we should change `@Id` to represent the document field `_key` instead, like `@Key` currently does. This eliminates the need of having two fields (for `@Id` and `@Key`) when using user generated keys.

**Comment by sigh-man** [comment]
Hi,  Will this also be added to the 1.x.x branch?  (I haven't upgraded spring data yet)

**Comment by mpv1989** [comment]
Yes, arangodb-spring-data 3 will require spring-data 2

**Comment by mpv1989** [comment]
Implementation done. Feature will be included in the upcoming 3.0.0 release
