### ISSUE TITLE
The way collection name is obtained from id needs to be optimized

### ISSUE THREAD

**Issue by haqer1** [arangodb/spring-data#85]
1.    now 2 substrings are generated, whereas only 1 is needed.
2.    now an array of size 2 is allocated, which is not needed at all.

P.S. The 3rd inefficiency from issue #67 is not encountered in the code yet, but sooner or later there will be duplication as well, unless this issue is fixed:
3.    there is code duplication.
So item 3. can be counted as a likely future issue.

**Comment by haqer1** [comment]
Following on the P.S. above, another one of my PRs already uses the new method in #86.

**Comment by mpv1989** [comment]
@haqer1 Thanks for reporting and fixing
