### ISSUE TITLE
All PR merges should reference the PR (or the issue for which it is submitted) & have an accurate comment

### ISSUE THREAD

**Issue by haqer1** [arangodb/spring-data#89]
E.g.:
https://github.com/arangodb/spring-data/commit/558d17a1863e10a7f593997c375df3064c3a6637
references neither PR #68 nor issue #67. 
And the comment 
> Extract determineDocumentKeyFromId() into Util class 

is misleading because it doesn't reflect any of the issues fixed:

> 1. now 2 substrings are generated, whereas only 1 is needed. 
> 2. now an array of size 2 is allocated, which is not needed at all. 
> 3. there is code duplication.

OR 
the title on the PR:

> An optimization for memory and cpu usage, and code reuse

**Comment by mpv1989** [comment]
thank you for the advice, we will try to pay more attention to it in the future. In any case you are right, a reference to the PR is not wrong
